

services:
  db:
    image: postgres:16.2
    container_name: cotizacion_envios_db
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


  redis:
    image: redis:7.0.10
    container_name: cotizacion_envios_redis
    restart: always
    ports:
      - 6379:6379
  